require: rubocop-thread_safety
require: rubocop-rspec

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rack-cors.rb'
    - 'spec/support/shoulda-matchers.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/documentation/**/*.rb'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/documentation/**/*.rb'
